### ISSUE TITLE
자기소개 작성 후 재 변경 시 디폴트 값으로 공백 설정되어 있음

### ISSUE THREAD

**Issue by YangTaeyoung** [InhaBas/Inhabas.com#121]
아무것도 건드리지 않은 수정 창임 (디폴트로 앞에 공백 생김)
<img width="610" alt="image" src="https://user-images.githubusercontent.com/59782504/172164814-977a1fa1-93d5-41a2-84aa-38493c3c595c.png">

**Comment by Dong-Hyeon-Yu** [comment]
호오 html 파일에서 탭 띄어쓰기가 있을 확률이..
