### ISSUE TITLE
강의/스터디 필터바

### ISSUE THREAD

**Issue by Dong-Hyeon-Yu** [InhaBas/Inhabas.com#16]
필터바.. 이대로... 내버려두실겁니까...

**Comment by Yejin0O0** [comment]
이번주 내로 고쳐두겠습니다 형님

일단 vue 구현을 못하였으니 그냥 없애는 방향(주석처리)으로 먼저 진행할게요!

**Comment by Dong-Hyeon-Yu** [comment]
네 좋습니다~
